round = 0

store-count = 10
region-count = 200

key-length = 56
replica = 3

leader-update-ratio = 0.06
epoch-update-ratio = 0.04
space-update-ratio = 0.15
flow-update-ratio = 0.35
no-update-ratio = 0.0

sample = false
