[Leaders]
[[Leaders.Leader]]
    KeyStart  = "757365727461626C653A7573657236303335383839313432303634363533353339"
    KeyEnd    = "757365727461626C653A7573657236383938343035303036353538323235323933"   
    StartTime = "2019-09-05T14:55:00+08:00"
    EndTime   = "2019-09-30T10:30:00+08:00"
    [[Leaders.Leader.Stores]]
        [[Leaders.Leader.Stores.StoreLabel]]
            Key   = "zone"
            Value = "z3"
        [[Leaders.Leader.Stores.StoreLabel]]
            Key   = "rack"
            Value = "r3"
        [[Leaders.Leader.Stores.StoreLabel]]
            Key   = "host"
            Value = "h3"
[Regions]
[[Regions.Region]]
    KeyStart  = "757365727461626C653A7573657235333633393437383939343235303336373432"
    KeyEnd    = "757365727461626C653A7573657236303335383839313432303634363533353339"
    StartTime = "2019-09-05T07:30:00+08:00"
    EndTime   = "2019-09-30T10:30:00+08:00"
    [[Regions.Region.Stores]]
        [[Regions.Region.Stores.StoreLabel]]
            Key   = "zone"
            Value = "z1"
        [[Regions.Region.Stores.StoreLabel]]
            Key   = "rack"
            Value = "r1"
        [[Regions.Region.Stores.StoreLabel]]
            Key   = "host"
            Value = "h1"
    [[Regions.Region.Stores]]
        [[Regions.Region.Stores.StoreLabel]]
            Key   = "zone"
            Value = "z2"
        [[Regions.Region.Stores.StoreLabel]]
            Key   = "rack"
            Value = "r2"
        [[Regions.Region.Stores.StoreLabel]]
            Key   = "host"
            Value = "h2"
    [[Regions.Region.Stores]]
        [[Regions.Region.Stores.StoreLabel]]
            Key   = "zone"
            Value = "z4"
        [[Regions.Region.Stores.StoreLabel]]
            Key   = "rack"
            Value = "r4"
        [[Regions.Region.Stores.StoreLabel]]
            Key   = "host"
            Value = "h4"
